name             'mysql-cluster'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql-cluster'
long_description 'Installs/Configures mysql-cluster'
version          '0.1.0'

depends 'mysql'
depends 'cron'
depends 'nfs'
